plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.0.0-beta.2"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.

    maven {
        url "https://maven.shedaniel.me"
    }

    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        url "https://maven.terraformersmc.com/"
    }

    maven {
        url "https://squiddev.cc/maven/"
        content {
            includeGroup("cc.tweaked")
        }
    }

    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    flatDir {
        dir 'libs'
    }
}

fabricApi {
    configureDataGeneration {
        setClient(true)

        getOutputDirectory().set(getProject().file("src/generated/resources"))

        setModId(project.modid)
    }

    loom.runConfigs.datagen.runDir("run")
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // Uncomment the following line to enable the deprecated Fabric API modules.
    // These are included in the Fabric API production distribution and allow you to update your mod to the latest modules at a later more convenient time.

    // modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"

    // Team Reborn: Fabric energy
    include api('teamreborn:energy:5.0.0') {
        exclude(group: "net.fabricmc.fabric-api")
    }

    // Energized Power dependency
    compileOnlyApi "curse.maven:energized-power-782147:8610442"

    localRuntime "curse.maven:energized-power-782147:8610442"

    // Regions Unexplored integration
    compileOnlyApi "curse.maven:regions-unexplored-659110:8490005"

    localRuntime "curse.maven:regions-unexplored-659110:8490005"
    localRuntime "curse.maven:lithostitched-936015:8378499"
    localRuntime 'com.electronwill.night-config:core:3.7.4'
    localRuntime 'com.electronwill.night-config:toml:3.7.3'
    localRuntime "curse.maven:terrablender-fabric-565956:7933873"
    localRuntime "curse.maven:forge-config-api-port-547434:8218664"

    // For more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html
    localRuntime "mezz.jei:jei-26.1.2-fabric:29.6.2.31"
    //localRuntime "me.shedaniel:RoughlyEnoughItems-fabric:20.0.811"
    //localRuntime "dev.emi:emi-fabric:1.1.13+1.21.1"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

//Show more errors for porting
afterEvaluate {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "2000"
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}

publishMods {
    displayName = "Energized Power - RU - " + "26.1.x" + " - v" + project.mod_version.split("\\+")[0] + " [Fabric]"
    changelog = new File("CHANGELOG.md").exists()?new File("CHANGELOG.md").getText("UTF-8"):""
    type = STABLE
    file = jar.archiveFile
    modLoaders.add("fabric")

    dryRun = project.mod_version.contains("dev")

    if(project.hasProperty('MODRINTH_TOKEN')) {
        modrinth {
            accessToken = getProperty('MODRINTH_TOKEN') as String
            projectId = "pFrEfXHl"
            minecraftVersionList("26.1, 26.1.1, 26.1.2")
            requires("fabric-api", "energized-power", "regions-unexplored")
        }
    }

    if(project.hasProperty('CURSEFORGE_TOKEN')) {
        curseforge {
            accessToken = getProperty('CURSEFORGE_TOKEN') as String
            projectId = "1108229"
            minecraftVersionList("26.1, 26.1.1, 26.1.2")
            requires("fabric-api", "energized-power", "regions-unexplored")
            client = true
            server = true
            javaVersions.add(JavaVersion.VERSION_25)
        }
    }
}

//Dummy task to fix post sync error caused by NeoGradle
tasks.register("idePostSync") {

}
